### ISSUE TITLE
Wayback machine feature not working

### ISSUE THREAD

**Issue by ecchi** [NocturnalNebula/lit-dl#1]
```
Finding story title...
Finding page count...
Finding author username...
Saved Page 1 of 5...
Saved Page 2 of 5...
Saved Page 3 of 5...
Saved Page 4 of 5...
Saved Page 5 of 5...
Traceback (most recent call last):
  File "/Users/ecchi/code/lit-dl/lit-dl.py", line 484, in <module>
    main_menu()
  File "/Users/ecchi/code/lit-dl/lit-dl.py", line 397, in main_menu
    download_wb_story(url)
  File "/Users/ecchi/code/lit-dl/lit-dl.py", line 260, in download_wb_story
    header = '<h3>' + title + '</h3><p>' + username + '</p><p>' + url + '</p><p>--------------</p>'
                                           ^^^^^^^^
NameError: name 'username' is not defined

```
I decided maybe it was just having a hard time parsing the author, so I just manually assigned "author" as a string for username.  That eliminates the error, but the output is just
```
SampleStoryTitle

AUTHOR

https://web.archive.org/web/20211110192554/https://www.literotica.com/s/sample-story-link
#Sample link, not real

--------------

Note: You can change font size, font face, and turn on dark mode by clicking the "A" icon tab in the Story Info Box.
#This line repeats for every page of the story, so the program does traverse pages properly, just not content

```
Nothing else.

The normal story downloading seems to work fine, its just wayback machine content are not parsing correctly?

**Comment by NocturnalNebula** [comment]
You were right - at the time, only the 'classic' format was supported. However, Wayback Machine support is now full. Any Literotica site format (or scheme) will now work fine with v1.3 of litstash (formerly lit-dl).
